#!/bin/bash
# Progammer : ALIF FUSOBAR - <master@itsecurity.id> - @Xcod3bughunt3r - <https://www.itsecurity.id>
# Program ini dapat digunakan untuk personal ataupun komersial.

again='y'
while [[ $again == 'Y' ]] || [[ $again == 'y' ]];
do
clear
echo "=================================================================";
echo " Xcod3-Pangeran Server for Ubuntu 16.04                          ";
echo " Progammer : ALIF FUSOBAR - www.itsecurity.id                              ";
echo " Version 2.91 - 10/08/2022                                       ";
echo "=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=";
echo " Installasi server & konfigurasi                                 ";
echo " [1]  Install Xcod3-Pangeran Server                              ";
echo " [2]  Setting IP Address untuk eth0                              ";
echo " [3]  Install Apache2, Mysql-server, phpmyadmin                  ";
echo " [4]  Install Virtualhost                                        ";
echo " [5]  Setting Virtualhost                                        ";
echo " [6]  Edit Konfigurasi pada php.ini                              ";
echo " [7]  Edit Konfigurasi pada apache2.conf                         ";
echo " [8]  Install DNS Server                                         ";
echo " [9]  Masukkan domain baru pada DNS Server                       ";
echo " [10] Setting domain yang sudah ada di DNS Server                ";
echo " [11] Edit /etc/hosts                                            ";
echo " [12] Install Samba Server                                       ";
echo " [13] Share /home/share tanpa password : read only               ";
echo " [14] Share /home/share tanpa password : : read & write          ";
echo " [15] Share /home/share dipassword : read only                   ";
echo " [16] Share /home/share dipassword : read & write                ";
echo " =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-";
echo " Log Server                                                      ";
echo " [17] Cek file access.log.*                                      ";
echo " [18] Lihat log pengunjung website (real time)                   ";
echo " [19] Lihat semua log pengunjung website                         ";
echo " [20] Pindah ke X-code Pandawa router                            ";
echo " [21] Reboot                                                     ";
echo " [22] Exit                                                       ";
echo "=================================================================";
read -p " Masukkan Nomor Pilihan Anda antara [1 - 22] : " choice;
echo "";
case $choice in
1)  if [ -z "$(sudo ls -A /etc/default/grub)" ]; then
    echo "Tidak terdeteksi grub, anda yakin pakai Ubuntu 16.04 ?"
    else
    sudo passwd root
    sudo apt-get install shellinabox
    sudo rm /etc/profile.d/myscript.sh 
    sudo ln -s /Xcod3-Pangeran/xcod3server /etc/profile.d/myscript.sh
    sudo cp /Xcod3-Pangeran/shellinabox /etc/default
    sudo cp /Xcod3-Pangeran/support/rc.local /etc
    sudo cp /Xcod3-Pangeran/support/grub /etc/default/grub
    sudo grub-mkconfig -o /boot/grub/grub.cfg
    sudo cp /Xcod3-Pangeran/support/resolved.conf /etc/systemd/
    sudo systemctl restart systemd-resolved
    sudo cp /Xcod3-Pangeran/support/interfaces /etc/network/
    sudo nano /etc/network/interfaces
    read -p "Tekan enter untuk restart"
    sudo systemctl reboot -i
    fi
    ;;
2)  if [ -z "$(ls -l /etc/network/interfaces)" ]; then
    echo "Tidak terdeteksi ada /etc/network/interfaces"
    else
    sudo nano /etc/network/interfaces
    read -p "Apakah anda mau restart koneksi eth0 sekarang? y/n :" -n 1 -r
    echo 
        if [[ ! $REPLY =~ ^[Nn]$ ]]
        then
        sudo ip addr flush eth0 && sudo systemctl restart networking.service
        sudo ifconfig
        fi
    fi
    ;;
3)  read -p "Apakah anda mau yakin mau install apache2, mysql-server & phpmyadmin ? y/n :" -n 1 -r
    echo  ""
    if [[ ! $REPLY =~ ^[Nn]$ ]]
    then
    sudo apt-get install apache2
    echo "Apache2 sudah diinstall"
    sudo apt-get install mysql-server
    echo "DHCP Server sudah diinstall"
    sudo apt-get install phpmyadmin
    echo "PHPMyadmin sudah diinstall"
    fi
    ;;
4)  echo -n "Masukkan alamat domain / subdomain : "
    read namadomain
    if [ -z "$(ls -A /home/$namadomain/*)" ]; then
    echo "Installasi virtualhost dengan domain"
    sudo useradd -m $namadomain
    sudo passwd $namadomain
    sudo mkdir -p /home/$namadomain/public_html
    sudo chown -r $namadomain.$namadomain /home/$namadomain/public_html
    sudo chmod -R 755 /home/$namadomain
    sudo echo "Selamat datang di web Xcod3-Pangeran" >> /home/$namadomain/public_html/index.html
    sudo chmod 755 /home/$namadomain/public_html/index.html
    sudo chown $namadomain.$namadomain /home/$namadomain/public/index.html
    sudo cp /Xcod3-Pangeran/config/apache2.conf /etc/apache2/
    sudo cp /Xcod3-Pangeran/config/domain.conf /etc/apache2/sites-available/$namadomain.conf
    sudo nano /etc/apache2/sites-available/$namadomain.conf
    sudo a2ensite $namadomain.conf
    sudo service apache2 reload
    else
    echo "Domain yang anda masukkan sudah ada"
    fi
    ;;   
5)  echo -n "Masukkan alamat domain / subdomain : "
    read namadomain
    if [ -z "$(ls -A /etc/apache2/sites-available/$namadomain.conf)" ]; then
    echo "Domain tersebut tidak ada, install virtualhost dulu"
    else
    sudo nano /etc/apache2/sites-available/$namadomain.conf
    sudo a2ensite $namadomain.conf
    sudo service apache2 reload
    fi
    ;;
6)  sudo nano /etc/php/7.0/apache2/php.ini
    ;;   

7)  sudo nano /etc/apache2/apache2.conf
    ;;

8)  sudo apt-get install bind9
    ;;

9)  echo -n "Masukkan alamat domain yang akan diredirect : "
    read namadomain2
    if [ -z "$(ls -A /etc/bind/db.$namadomain2)" ]; then
    sudo cp /Xcod3-Pangeran/db.local /etc/bind/db.$namadomain2
    sudo nano /etc/bind/db.$namadomain2
    sudo cp /Xcod3-Pangeran/config/named.conf /etc/bind/named.conf
    sudo nano /etc/bind/named.conf
    sudo service bind9 restart
    else
    echo "Domain yang anda redirect sudah ditambahkan sebelumnya"
    fi
    ;;

10)  echo -n "Masukkan alamat domain yang akan diedit : "
    read namadomain3
    if [ -z "$(ls -A /etc/bind/db.$namadomain3)" ]; then
    echo "Domain yang anda masukkan belum ditambahkan, silahkan tambahkan dulu"
    else 
    sudo nano /etc/bind/db.$namadomain3
    sudo nano /etc/bind/named.conf
    sudo service bind9 restart
    fi
    ;;

11) sudo nano /etc/hosts
    ;;

12)  if [ -z "$(ls -A /etc/samba/smb.conf)" ]; then
    echo "Install Samba"
    sudo apt-get install samba
    else
    echo "Samba sudah diinstall"
    fi
    ;;

13) if [ -z "$(ls -A /etc/samba/smb.conf)" ]; then
    echo "Samba belum diinstall"
    else
    sudo mkdir /home/share
    sudo cp /Xcod3-Pangeran/config/samba1/smb.conf /etc/samba
    sudo service smbd restart
    sudo chmod o-w /home/share 
    fi
    ;;

14) if [ -z "$(ls -A /etc/samba/smb.conf)" ]; then
    echo "Samba belum diinstall"
    else
    sudo mkdir /home/share
    sudo cp /Xcod3-Pangeran/config/samba2/smb.conf /etc/samba
    sudo service smbd restart
    sudo chmod o+w /home/share
    fi
    ;;

15) if [ -z "$(ls -A /etc/samba/smb.conf)" ]; then
    echo "Samba belum diinstall"
    else
    sudo useradd -m hacker
    sudo passwd hacker
    sudo mkdir /home/share
    sudo cp /Xcod3-Pangeran/config/samba3/smb.conf /etc/samba
    sudo smbpasswd -a hacker
    sudo chown -R hacker.hacker /home/share
    sudo chmod u-w /home/share    
    sudo service smbd restart
    fi
    ;;

16) if [ -z "$(ls -A /etc/samba/smb.conf)" ]; then
    echo "Samba belum diinstall"
    else
    sudo useradd -m hacker
    sudo passwd hacker
    sudo mkdir /home/share
    sudo cp /Xcod3-Pangeran/config/samba4/smb.conf /etc/samba
    sudo smbpasswd -a hacker
    sudo chown -R hacker.hacker /home/share
    sudo chmod u+w /home/share
    sudo service smbd restart
    fi
    ;;

17) if [ -z "$(ls -A /var/log/apache2/access.log*)" ]; then
    echo "Tidak terdeteksi access.log untuk apache2"
    else
    sudo ls -l /var/log/apache2/access.log*
    fi
    ;;
18) if [ -z "$(ls -A /var/log/apache2/access.log)" ]; then
    echo "Tidak terdeteksi access.log untuk apache2"
    else
    sudo tail -f /var/log/apache2/access.log
    fi
    ;;

19) if [ -z "$(ls -A /var/log/apache2/access.log)" ]; then
    echo "Tidak terdeteksi access.log untuk apache2"
    else
    sudo nano /var/log/apache2/access.log
    fi
    ;;

20) sudo rm /etc/profile.d/myscript.sh 
    sudo ln -s /Xcod3-Pangeran/config/xcod3router /etc/profile.d/myscript.sh 
    read -p "Tekan enter untuk restart"
    sudo systemctl reboot -i
    ;;

21) read -p "Apakah anda yakin akan restart? y/n :" -n 1 -r
    echo 
    if [[ ! $REPLY =~ ^[Nn]$ ]]
    then
    sudo systemctl reboot -i
    fi
    ;;

22) ;;
*)    echo "Maaf, menu tidak ada"
esac
echo ""
echo "Xcod3-Pangeran Server"
echo "Oleh ALIF FUSOBAR - master@itsecurity.id - www.itsecurity.id"
echo ""
echo -n "Kembali ke menu? [y/n]: ";
read again;
while [[ $again != 'Y' ]] && [[ $again != 'y' ]] && [[ $again != 'N' ]] && [[ $again != 'n' ]];
do
echo "Masukkan yang anda pilih tidak ada di menu";
echo -n "Kembali ke menu? [y/n]: ";
read again;
done
done

